name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    if: github.ref == 'refs/heads/main'
    name: Build, test and publish to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21
          cache: gradle
      - name: Run lint
        run: ./gradlew ktlintCheck
      - name: Run tests
        run: ./gradlew test
      - name: Publish
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
